#!/usr/bin/env bash
archive_path="$HOME/github-archive/2015"
archive_dest="$HOME/github-archive/2015-bz"
total=$(ls -l "${archive_path}" | wc -l)
i=0
pushd "$archive_path"
for src in *.gz; do
    progress=$(echo "scale=2;($i/$total)*100" | bc)
    echo "${progress}% (${i}/${total})- $f"
    dest=${src%.gz}.bz2
    orig_size=$(gzip -l $src | tail -1 | awk '{print $2}')
    zcat $src | pv -pterba -s $orig_size | bzip2 -zc > "${archive_dest}/${dest}"
    ((i++))
done
popd
