#!/usr/bin/env python3
import os, sys
abspath = os.path.abspath(__file__)
dname = os.path.dirname(abspath)
os.chdir(os.path.join(dname, "app"))
sys.path.insert(0, os.curdir)

from flask.ext.script import Manager, Server, Shell
from app.github_contributions import app, mongo

def _make_context():
    return dict(
        app=app,
        mongo=mongo
    )

manager = Manager(app)
manager.add_command('runserver', Server(host='0.0.0.0', use_debugger=True))
manager.add_command('shell', Shell(make_context=_make_context))

if __name__=='__main__':
    manager.run()
