#!/usr/bin/env python
from flask.ext.script import Manager, Shell
import app

def _make_context():
    return dict(
        app=app.app,
        mongo=app.mongo
    )

manager = Manager(app.app)
manager.add_command('shell', Shell(make_context=_make_context))

if __name__=='__main__':
    manager.run()
