export GHC_ENV="production"
export GHC_LOCKFILE_PATH="/tmp/archive-processor.lock"
export GHC_EVENTS_PATH="/srv/github-archive/events"
export GHC_TIMELINE_PATH="/srv/github-archive/timeline"
export GHC_TRANSFORMED_PATH="/srv/github-archive/transformed"
export GHC_LOADED_PATH="/srv/github-archive/loaded"
export GHC_LOG_PATH="/srv/github-archive/logs"
export GHC_ROLLBAR_TOKEN="{{ rollbar_token }}"
