#!/bin/bash
MAILTO="liambowen@gmail.com"
WORKING_PATH="/github-contributions"
PROCESSOR="/github-contributions/util/archive-processor"
PYTHON="/srv/venv/bin/python3"

export GHC_LOCKFILE_PATH="/tmp/archive-processor.lock"
export GHC_EVENTS_PATH="/github-archive/events"
export GHC_TIMELINE_PATH="/github-archive/timeline"
export GHC_TRANSFORMED_PATH="/github-archive/transformed"
export GHC_LOADED_PATH="/github-archive/loaded"
export GHC_LOG_PATH="/github-archive/logs"

echo "GHCA Archive Processor"
/usr/bin/uptime

# Don't even try to run multiple copies
# If we do, they'll just get queued, but then we might have a lot of processes.
if [[ -f "${GHC_LOCKFILE_PATH}" ]];
then
    echo "archive-processor already running (lockfile: ${GHC_LOCKFILE_PATH})"
    exit 1
fi

/bin/mkdir -p "${WORKING_PATH}"
cd "${WORKING_PATH}"

${PYTHON} ${PROCESSOR} 'process'
