#!/usr/bin/env python3
# Works only for archives from 2015-01-01 -> Present
from datetime import datetime
from datetime import timezone
from pprint import pprint
from termcolor import colored
import argparse
import csv
import dateutil.parser
import fileinput
import glob
import gzip
import itertools
import json
import logging
import os
import os.path
import re
import sys
import urllib.parse


__version__ = '0.0.1'


if __name__=='__main__':

    parser = argparse.ArgumentParser(description='Import GitHub archive files')
    parser.add_argument('--events-path')
    parser.add_argument('--done-path')
    args = parser.parse_args()

    main(args)
