#!/bin/bash
set -e

cd $( dirname "${BASH_SOURCE[0]}" )/..

echo "deploying from $(pwd)"

if [[ $EUID -ne 0 ]];
then
    echo "deployment must be done as root" 1>&2
    exit 1
fi

# determine who the owner of the thing is going to be
owner=''
id -u 'http' > /dev/null 2>&1 && owner='http'
id -u 'www-data'  > /dev/null 2>&1 && owner='www-data'
if [[ -z "${owner}" ]];
then
    echo "neither users exist: http or www-data. not sure who should own the files."
    exit 1
fi
echo "will change owner to ${owner}:${owner}"

wanted_branch="master"
current_branch="$(git rev-parse --abbrev-ref HEAD)"

if [[ $current_branch != $wanted_branch ]];
then
    echo "cannot deploy branch: ${current_branch} to production (must be ${wanted_branch})" 1>&2
    exit 1
fi

current_release="$(git describe --long --dirty)"
dirty_pattern="-dirty$"
if [[ $current_release =~ $dirty_pattern ]];
then
    echo "this repository is dirty (${current_release}). please clean it."
    #exit 1
fi

echo "making /tmp/deploy"
[[ -d /tmp/deploy ]] && rm -rf /tmp/deploy
mkdir -p /tmp/deploy
echo "copying app to /tmp/deploy"
cp -rv ./app /tmp/deploy
cp ./requirements.txt /tmp/deploy
cd /tmp/deploy
echo "now in $(pwd)"
echo "making venv"
virtualenv --python=/usr/bin/python3 venv
echo "installing packages to virtualenv"
./venv/bin/pip install -r /tmp/deploy/requirements.txt

echo "changing owner to ${owner}:${owner}"
chown -R "${owner}:${owner}" /tmp/deploy

echo "Emperor status:"
systemctl status emperor.uwsgi

read -p "finalize deployment? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    mv -f /srv/app "/srv/app-$(date +%s)"
    mv -f /srv/venv "/srv/venv-$(date +%s)"
    mv -f /tmp/deploy/app /srv/
    mv -f /tmp/deploy/venv /srv/
fi

echo "restarting emperor:"
systemctl restart emperor.uwsgi

echo "Emperor status:"
systemctl status emperor.uwsgi

echo "clean up /tmp/deploy if you want"
cowsay "Deployment complete!"
