#!/usr/bin/env python3
# -*-python-*-
import sys
import os
import gzip
import glob
import logging
import json

PREFIX_LENGTH = 4

logging.basicConfig(level=logging.INFO)
logger = logging

input_dir, output_dir = sys.argv[1:]

filenames = glob.glob(os.path.join(input_dir,'*.json.gz'))
logger.info("processing {} json files".format(len(filenames)))

def prefix(username):
    return username[:PREFIX_LENGTH]

def route_event(event):
    username = event['_user_lower']
    user_fn = "{}.json".format(prefix(username))
    with open(os.path.join(output_dir, user_fn), 'at') as user_file:
        print(json.dumps(event), file=user_file)

def main():
    for file_i, file_path in enumerate(filenames):
        logger.info("processing {}".format(file_path))
        input_file = gzip.open(file_path, 'rt')
        for line_i, line in enumerate(input_file):
            event = json.loads(line)
            route_event(event)

if __name__=='__main__':
    main()
