#!/usr/bin/env python3
from __future__ import print_function
import os
import sys
import glob
import gzip
import json


def usernames():
    """ generate list of distinct usernames from transformed data
    """
    users = set()
    files = list(glob.glob(os.path.join(
        os.environ['GHC_TRANSFORMED_PATH'], '*.json.gz')))
    print("looking in", len(files), "files")
    for ix, path in enumerate(files):
        with gzip.open(path, 'rt', encoding='utf-8') as f:
            events = (json.loads(line) for line in f)
            users |= set((e.get('_user_lower') for e in events))
        print(ix, "\t", len(files))

    users = sorted(users)

    with open('users.txt', 'wt') as f:
        for u in users: print(u, file=f)

    print("there are", len(users), "users")

if __name__=='__main__':
   usernames()
