#!/bin/bash
set -e
for event_file in $GHC_EVENTS_PATH/*.json.gz
do
    users_event_file="${event_file}.users.txt"
    if [[ ! -f $users_event_file ]]
    then
       zcat $event_file |
           jq .actor.login |
           tr '[:upper:]' '[:lower:]' |
           sort -u > $users_event_file
    fi
done

sort -u $GHC_EVENTS_PATH/*.users.txt >! /tmp/ghc-users-uniq.txt
mv tmp/ghc-users-uniq.txt $GHC_EVENTS_PATH/users.txt
